config/routes.rb
Rails.application.routes.draw do


  root :to => "home#index"

  resources :programmers
  resources :clients
  resources :projects
  resources :schedules

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/programmer.rb
class Programmer < ApplicationRecord
    has_and_belongs_to_many :projects
    has_many :tasks
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  before_action :set_programmer, only: [:show, :edit, :update, :destroy]
  def index
    @programmers = Programmer.all
    respond_to do |format|
      format.html 
      format.json { render json: @programmers, status: :ok }
    end
  end

  def show
    @programmer = Programmer.find(params[:id])
  end

  def new
    @programmer = Programmer.new
  end

  def edit
    @programmer = Programmer.find(params[:id])
  end

  def create
    @programmer = Programmer.new(programmer_params)

    respond_to do |format|
      if @programmer.save
        format.html { redirect_to @programmer, notice: 'Programador cadastrado' }
        format.json { render :show, status: :created, location: @programmer }
      else
        format.html { render :new }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end 

  def update
    
    respond_to do |format|
      if @programmer.update(programmer_params)
        format.html { redirect_to @programmer, notice: 'Programador atualizado' }
        format.json { render :show, status: :ok, location: @programmer }
      else
        format.html { render :edit }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end 

  def destroy

    respond_to do |format|
      if @programmer.destroy
        format.html { redirect_to programmers_url, notice: 'Programador removido' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end 

  private
    def set_programmer 
      @programmer = Programmer.find(params[:id])
    end

    def programmer_params
      params.require(:programmer).permit(:name)
    end 
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/programmers/_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sx-12">
        <%= form_for(programmer) do |f| %>
            <% if programmer.errors.any? %>
                <div id="error_explanation">
                    <h2>
                        <%= pluralize(programmer.errors.count, "error")%>
                            Impossível salvar informações deste Programmador:
                    </h2>
                    <ul>
                        <% programmer.errors.full_messages.each do |message| %>
                            <li>
                                <%= message %>
                            </li>
                            <% end %>
                    </ul>
                </div>
                <% end %>
                    <div class="form-group">
                        <%= f.label :name %>
                            <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class="actions">
                        <%= f.submit 'Salvar', class: 'btn btn-primary btn-block' %>
                    </div>
                    <% end %>
    </div>
</div>

app/views/programmers/edit.html.erb
<h1>Editando Programador</h1>
<%= render 'form', programmer: @programmer %>
<%= link_to 'Mostrar', programmer_path(@programmer), class: 'btn btn-info' %>
<%= link_to 'Voltar', programmers_path, class: 'btn btn-default' %>

app/views/programmers/index.html.erb
<h1>Programadores</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th colspan="3">Ações</th>
        </tr>
    </thead>

    <tbody>
        <% @programmers.each do |programmer| %>
            <tr>
                <td>
                    <%= programmer.id %>
                </td>
                <td>
                    <%= programmer.name %>
                </td>
                <td>
                    <%= link_to 'Mostrar', programmer_path(programmer), class: 'btn btn-primary' %>
                </td>
                <td>
                    <%= link_to 'Editar', edit_programmer_path(programmer), class: 'btn btn-warning' %>
                </td>
                <td>
                    <%= link_to t('delete'), programmer_path(programmer),
                    class: 'btn btn-danger', method: :delete,
                      data: {
                        title: t('attention'),
                        confirm: t('confirm_exclusion') + programmer.name + '?',
                        commit: t('delete'), cancel: t('cancel')} %>
                </td>
            </tr>
            <% end %>
    </tbody>
</table>
<br>
<%= link_to 'Novo Programmador', new_programmer_path, class: 'btn btn-primary' %>

app/views/programmers/new.html.erb
<h1>Novo Programador</h1>
<%= render 'form', programmer: @programmer %>
    <%= link_to 'Voltar', programmers_path, class: 'btn btn-default' %>

app/views/programmers/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>Programador:</strong>
  <%= @programmer.name %>
</p>

<p>
  <strong>ID:</strong>
  <%= @programmer.id %>
</p>

<%= link_to 'Editar', edit_programmer_path(@programmer), class: 'btn btn-warning' %>
<%= link_to 'Voltar', programmers_path, class: 'btn btn-secundary' %>