config/routes.rb
Rails.application.routes.draw do


  root :to => "home#index"

  resources :programmers
  resources :clients
  resources :projects
  resources :schedules

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  belongs_to :project
  has_many :sprints
  has_many :tasks, through: :sprints
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @schedules = Schedule.new(schedule_params)
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def edit
  end

  def create
    @schedule = Schedule.new(schedule_params)
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Cronograma definido'}
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Cronograma atualizado'}
        format.json { render json: @schedule, status: :updated, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @schedule.destroy
        format.html { redirect_to schedules_url, notice: 'Cronograma removido'}
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end
    def schedule_params
      params.require(:schedule).permit(:initial_date, :final_date)
    end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'dd-mm-yyyy', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'DD-MM-AAAA'
    end
  end
end

app/views/schedules/_fields.html.erb
<div class="form-group">
  <%= s.label t('initial_date') %>
  <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
    <div class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </div>
  <%= datepicker_input s, :initial_date %>
</div>
</div>
<div class="form-group">
  <%= s.label t('final_date') %>
  <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
    <div class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </div>
  <%= datepicker_input s, :final_date %>
</div>
</div>

<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/schedules/edit.html.erb
<h1>Schedules#edit</h1>
<p>Find me in app/views/schedules/edit.html.erb</p>

app/views/schedules/index.html.erb
<h1>Schedules#index</h1>
<p>Find me in app/views/schedules/index.html.erb</p>

app/views/schedules/new.html.erb
<h1>Criando Crongrama</h1>
<%= form_for(@schedule) do |s| %>
  <%= render '/schedules/fields', s: s %>

  <button type="submit" class="btn btn-success btn-block">Salvar</button>
<% end %>
<br>
<%= link_to 'Voltar', schedules_path, class: 'btn btn-default' %>

app/views/schedules/show.html.erb
<h1>Schedules#show</h1>
<p>Find me in app/views/schedules/show.html.erb</p>