config/routes.rb
Rails.application.routes.draw do


  root :to => "home#index"

  resources :programmers
  resources :clients
  resources :projects
  resources :schedules

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :projects
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Cliente cadastrado' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Cliente atualizado' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    respond_to do |format|
      if @client.destroy
        format.html { redirect_to clients_url, notice: 'Cliente removido' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :apelido)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sx-12">
    <%= form_for(client) do |f| %>
    <% if client.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(client.errors.count, "error")%>
        Impossível salvar informações deste Cliente:
      </h2>
      <ul>
        <% client.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.label t('name') %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label t('apelido') %>
      <%= f.text_field :apelido, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Salvar', class: 'btn btn-primary btn-block' %>
    </div>
    <% end %>
  </div>
</div>

app/views/clients/edit.html.erb
<h1>Editando Cliente</h1>
<%= render 'form', client: @client %>
<%= link_to 'Mostrar', client_path(@client), class: 'btn btn-info' %>
<%= link_to 'Voltar', clients_path, class: 'btn btn-default' %>

app/views/clients/index.html.erb
<h1>Clientes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <%  %>
    <%=  %>
    <% @clients.each do |client| %>
    <tr>
      <td>
        <%= client.id %>
      </td>
      <td>
        <%= client.name %>
      </td>
      <td>
        <%= link_to 'Mostrar', client_path(client), class: 'btn btn-primary' %>
      </td>
      <td>
        <%= link_to 'Editar', edit_client_path(client), class: 'btn btn-warning' %>
      </td>
      <td>
        <%= link_to 'Remover', client_path(client), class: 'btn btn-danger',
                    method: :delete, data: { confirm: 'Confirma remoção? Ação irreversível!!!'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Novo Cliente', new_client_path, class: 'btn btn-primary' %>

app/views/clients/new.html.erb
<h1>Novo Cliente</h1>
<%= render 'form', client: @client %>
<%= link_to 'Voltar', clients_path, class: 'btn btn-default' %>

app/views/clients/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @client.name %>
</p>

<p>
  <strong><%= t('apelido') %>:</strong>
  <%= @client.apelido %>
</p>

<p>
  <strong>ID:</strong>
  <%= @client.id %>
</p>

<%= link_to 'Editar', edit_client_path(@client), class: 'btn btn-warning' %>
<%= link_to 'Voltar', clients_path, class: 'btn btn-secundary' %>