config/routes.rb
Rails.application.routes.draw do


  root :to => "home#index"

  resources :programmers
  resources :clients
  resources :projects
  resources :schedules

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :schedule
  accepts_nested_attributes_for :schedule

  belongs_to :client
  has_and_belongs_to_many :programmers


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_clients, only: [:new, :edit, :create, :update]
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @project.build_schedule
  end

  def edit
    @project = Project.find(params[:id])
    @programmers = Programmer.all
    # if @project.schedule.blank?
    #   @project.schedule = Schedule.new
    # end
  end

  def create
    @project = Project.new(project_params)
    @project.schedule = set_schedule

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projeto cadastrado' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projeto atualizado' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_url, notice: 'Projeto removido' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def set_clients
      @clients = Client.all
    end
    def set_schedule
      @schedule = Schedule.new()
      @schedule.initial_date = params[:initial_date]
      @schedule.final_date = params[:final_date]
      @schedule
    end

    def project_params
      params.require(:project).permit(:description,
                                      :client_id,
                                      # schedule_attributes: [
                                      #   :initial_date,
                                      #   :final_date
                                      # ],
                                      programmer_ids: [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_errors.html.erb
<% if project.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(project.errors.count, "erro(s)")%>
    Impossível salvar informações deste Projeto:
  </h2>
  <ul>
    <% project.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/projects/_fields.html.erb
<div class="form-group">
  <%= f.label 'Descrição' %>
  <%= f.text_field :description, class: 'form-control' %>
</div>
<div class="form-group row">
  <div class="col-2">
    <%= f.label 'Cliente' %>
  </div>

  <div class="col-10">
  <%= f.collection_select(:client_id, @clients, :id, :name, class: 'form-control') %>
</div>
</div>

app/views/projects/_fields_programmers.html.erb
<div class="form-group">
  <%= f.hidden_field 'programmer_ids[]', value: [] %>
  <%= f.label "Programadores:"%>
  <%= f.collection_check_boxes :programmer_ids, Programmer.all, :id, :name do |b| %>
    <div class="collection_check_boxes">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sx-12">
    <%= form_for(project) do |f| %>
    <%= render 'errors', project: @project %>
    <div class="form-group">
      <%= f.label 'Descrição' %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="form-group row">
      <div class="col-2">
        <%= f.label 'Cliente' %>
      </div>

      <div class="col-10">
      <%= f.collection_select(:client_id, @clients, :id, :name, class: 'form-control') %>
    </div>
    </div>
    <%= f.fields_for :schedule do |s| %>
      <%= render 'schedules/fields', s: s, schedule: @schedule %>
    <% end %>
    <div class="actions">
      <%= f.submit 'Salvar', class: 'btn btn-primary btn-block' %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editando Projeto</h1>
<%= form_for(@project) do |f| %>
  <%= render 'errors', project: @project %>
  <%= render 'fields', f: f, project: @project %>

  <%= f.fields_for :schedule do |s| %>
    <%= render 'schedules/fields', s: s, schedule: @schedule %>
  <% end %>

  <%= render 'fields_programmers', f: f, project: @project, programmers: @programmers %>

  <button type="submit" class="btn btn-success btn-block">Atualizar</button>
<% end %>
<br>
<%= link_to 'Mostrar', project_path(@project), class: 'btn btn-info' %>
<%= link_to 'Voltar', projects_path, class: 'btn btn-default' %>

app/views/projects/index.html.erb
<p id="notice"></p>
<h1>Projetos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Descrição</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.id %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Mostrar', project_path(project), class: 'btn btn-info' %></td>
        <td><%= link_to 'Editar', edit_project_path(project), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Remover', project_path(project), class: 'btn btn-danger',
        method: :delete, data: { title: 'Atenção', confirm: 'Confirma exclusão? Ação irreversível!',
          commit: 'Remover', cancel: 'Cancelar' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Novo Projeto', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>Novo Projeto</h1>
<%= render 'form', project: @project %>
<%= link_to 'Voltar', projects_path, class: 'btn btn-default' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Projeto:</strong><%= @project.description %></p>
<p>
  <strong>Cliente:</strong><%= @project.client.name %></p>

  <span class="label label-success pull-right">
    <strong>Cronograma</strong>
  <p>  Início:
    <%= @project.schedule.initial_date %></p>
  <p>  Término:
    <%= @project.schedule.final_date %></p>
  </span>

<p>
  <% if @project.programmers.empty? %>
    <strong>Nenhum programador alocado ao projeto</strong>
  <% else %>
    <strong>Programadore(s):</strong>
    <ul>
      <% @project.programmers.each do |programmer| %>
        <li><%= programmer.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>
<%= link_to 'Editar', edit_project_path(@project), class: 'btn btn-warning' %>
<%= link_to 'Voltar', projects_path, class: 'btn btn-secundary' %>